model: "models/task1/task1.pt"
# model: "models/task2/v12_task1.pt"
source: "inputs"           # file or folder
save_dir: "app/outputs"
predictions_dir: "app/outputs/predictions"
stitched_dir: "app/outputs/stitched_preds"
imgsz: 640
conf: 0.20
iou: 0.20
jpeg_quality: 100 # Controls compression: 1-100 (higher is better quality but larger file)
line_width: 2 # Controls width of bounding box lines
font_size: 10 # Font size for labels
device: 0               # "0" for GPU 0, or "cpu"
save_txt: true             # YOLO txt outputs
save_conf: true
#Holds class names
classes:
  - Number 1
  - Number 2
  - Number 3
  - Number 4
  - Number 5
  - Number 6
  - Number 7
  - Number 8
  - Number 9
  - Alphabet A
  - Alphabet B
  - Alphabet C
  - Alphabet D
  - Alphabet E
  - Alphabet F
  - Alphabet G
  - Alphabet H
  - Alphabet S
  - Alphabet T
  - Alphabet U
  - Alphabet V
  - Alphabet W
  - Alphabet X
  - Alphabet Y
  - Alphabet Z
  - Up Arrow
  - Down Arrow
  - Right Arrow
  - Left Arrow
  - Stop sign

